### ISSUE TITLE
Trouble Installing With Ubuntu Linux

### ISSUE THREAD

**Issue by MggMuggins** [Guichaguri/BetterFps#7] opened 2016-02-05 03:08 UTC
As I say above, I use Ubuntu Linux. Let me explain just a few things here. I have a decent machine (Lenovo Yoga 3 14" with an i5 and 8GB RAM) and it can play MC with decent framerates (40-60 fps). However, if I get a heavily modded client (LOTR(Largest single mod I know) + NEI +Damage Indicators + Gravestone + Fastcraft), life gets interesting. For the most part, I can keep the FPS above 35-40 by decreasing graphics settings, however, I still have issues with the glowing enchantment overlay on equipment, and the glowing texture with LOTR elvish swords. I heard that FPS enhancement mods seem to hep with that kind of fps drop, so I set about finding a mod. Your's looked the best fit for this set of mods (Optifine has known issues with LOTR, FPSPlus doesn't seem necessarily legal), so I went to install. Now, like I said, I use Linux, and with that MultiMC (https://multimc.org). This machine only has 256GB on it's SSD, so I want to save space, which MultiMC is good for. I figured that the automatic installer you built for this mod was designed for windows, and trying to run the .JAR with Java produced an error (though it had to do with permissions rather than with directories, etc.). When placing the jar directly from the download into the mods folder of the instance I would like to install it to, and running the game, it won't load. Funny thing is, in MultiMC's modding gui, it shows it as a mod on the loader mods list, though it doesn't actually try to run the mod. I've attached a forge output file from trying to open that instance with your mod in the mods folder. Any ideas? A quick reply would be appreciated, but I realize you're busy(most mod developers are ; ) ), so I can wait. It's not terribly urgent.

The file for the forge output is attached. I opened minecraft to the title screen, and grabbed the file from there. I then used a search tool to find and replace my name (in paths and things) with six asterixes. That is all i edited.
[forge_log_multimc.txt](https://github.com/Guichaguri/BetterFps/files/118576/forge_log_multimc.txt)

**Comment by Guichaguri** [comment] 2016-02-05 11:07
I don't see any logs related to BetterFps.
In the current version, BetterFps only changes how sine and cosine are calculated.
Does it load without BetterFps? It might be a conflict with LOTR

Also, the installer works for any operational system, but it is designed for non-forge based installations

**Comment by MggMuggins** [comment] 2016-02-05 21:35
Yes, what it looks like is that your mod is not loading at all. I did try removing LOTR from the pack and loading and it did nothing. I then created an new instance (One I have been wanting to for a while), and had BetterFPS as the only mod along forge version 10.13.4.1492 for Minecraft 1.7.10. It still didn't load. I don't have the vanilla launcher on this machine to save space of course, so I couldn't test it with that. I may try re-downloading the mod and seeing if that helps.

EDIT: Re-downloading the mod and putting it in my test instance did no good. I'm going to try playing with the regular MC launcher and we shall see if it works.

EDIT: Placing this mod as the only mod in the mods folder in a regular MC installation, same specs as that MultiMC instance above doesn't work either. It simply doesn't load the mod. I want to make sure that I am doing this correctly. All I have to do is download the jar and place it in the mods folder, no unpacking required, correct?

**Comment by MggMuggins** [comment] 2016-02-05 22:04
Good News and bad news. I downloaded that old beta for 1.7.10 and installed it, and it loaded and everything. However, I noticed absolutely no improvement to my FPS in either vanilla or LOTR. Nor did it fix enchantment glow/elven sword overlay FPS drops. I do notice that the FPS meter on F3 does not notice the FPS drops that occur when the elven sword and Enchanted bow textures drop the FPS. Also, isn't F12 supposed to bring up a menu? I tried, and it didn't work. :/

**Comment by Guichaguri** [comment] 2016-02-05 22:43
You need Forge for just placing the mod in the mods folder
The F12 should have key conflicts, you can change it in the options
I'll make tests to see if I can reproduce the problem.

**Comment by MggMuggins** [comment] 2016-02-06 13:08
I'll check those key conflicts. Didn't think about that...

EDIT: The Old BetterFPS (Beta 1) that I can actually get to load does not appear to have F12 as a control. It isn't in the controls screen. I still can't get the new version to run.

**Comment by Guichaguri** [comment] 2016-02-06 19:26
I'm pretty sure the old BetterFps didn't had an option GUI.
I'll try BetterFps in the newest Forge version for 1.7.10

**Comment by kwiknik** [comment] 2016-02-12 19:44
I'm running Steam OS (Debian Wheezy) and have the same problem.

I have a number of other mods (only 3-4 e.g. OptiFine) installed into `$HOME/.minecraft/mods`, and they all load fine using the latest version of Forge with Minecraft client 1.8.9 .

However, BetterFps v1.2.0 isn't loaded - there's no mention of it in the Forge logs, and it's not visible in the Mods menu in-game.

I've also tried BetterFps v1.1.1 and v1.0.1 - same thing, they just aren't loaded, and there's no mention of them.

**Comment by kwiknik** [comment] 2016-02-12 20:51
I'm a software developer by trade, am happy to do whatever low level testing you like to resolve this, since I'd like to use your mod :)

**Comment by Guichaguri** [comment] 2016-02-12 22:02
It does not show in the mod list due to a missing feature in Forge, but it should load anyway.
No logs related to BetterFps?

Tell me which of these logs are not printed:
- Calling tweak class me.guichaguri.betterfps.tweaker.BetterFpsTweaker
- Patching Game Start...
- Patching Key Event...
- Patching Minecraft using **{Algorithm Name}** Algorithm

And, in case you are using Forge:
- Loading tweaker me.guichaguri.betterfps.tweaker.BetterFpsTweaker from **{BetterFps jar file}**

**Comment by MggMuggins** [comment] 2016-02-13 14:28
Just to clarify so that I can test, the log that MultiMC spits out is the log that I would find those things in, correct? I'm going to run the newest version of the mod and forge and see if it says any of those things.

**Comment by MggMuggins** [comment] 2016-02-13 14:32
Well, the log that I provided with this bug report has all of those things. I'm going to do a little more testing.

The second log had all of those things as well. Curiously, it says that it is patching using Riven's "Half", but the Config says it should be using full. The mod does not show up in my mod lists when the game is loaded though.

**Comment by Guichaguri** [comment] 2016-02-13 14:53
@MggMuggins try changing the algorithm, you can either use the F12 option screen or go directly into the config and set the algorithm to `random`. It's the easiest way to test if it's working (don't try to generate chunks using this algorithm, it will crash).
The random algorithm should make the game very freaky

Depending on your computer, some algorithms can be slower or have any or a small difference compared to vanilla.
You can open the installer to test the algorithms. No need to reinstall again, use it just to see which algorithm might reduce the lag

**Comment by Guichaguri** [comment] 2016-05-27 18:40
I'm closing this issue as no feedback was given for a long time. Feel free to reopen it whenever you want.

**Closed as completed by Guichaguri** 2016-05-27 18:40 UTC

**Comment by MggMuggins** [comment] 2016-05-30 17:16
Well, for some reason, the menu is now working. I'm going to test a few
algorithms and see what gets me the best FPS.
~Sam
