### ISSUE TITLE
Flailing Arms

### ISSUE THREAD

**Issue by Kore-Development** [Guichaguri/BetterFps#113] opened 2018-06-20 14:02 UTC
* Minecraft Version: 1.12.2
* BetterFps Version: 1.4.8
* Forge/LiteLoader Version (if any): 14.23.4.2708
* Crash Logs (if any): None
* Other Mods (if any): 
![Mods](https://i.gyazo.com/330653236311fd1608fb6ccaef7f2d9d.png)
* Video: [Click here](https://www.youtube.com/embed/YBvyHibX5GA) and [click here](https://www.youtube.com/embed/g5SLTHifcgk)
---
With Taylor's Algorithm I have flailing arms and I can not see where I'm going because my screen also goes crazy.

**Comment by Guichaguri** [comment] 2018-06-20 23:31
It's a known issue. It only happens in some specific computers, please, use another algorithm for now.

Duplicate of #62

**Closed as completed by Guichaguri** 2018-06-20 23:31 UTC
Labels: duplicate
