### ISSUE TITLE
Running the mod in dev environment (for debugging compatibility issue)

### ISSUE THREAD

**Issue by Niko-sk2x** [Guichaguri/BetterFps#60] opened 2017-05-21 14:06 UTC
I'm trying to debug this issue: https://github.com/OpenCubicChunks/CubicChunks/issues/184. To do that I'm trying to run BetterFPS in my mod dev environment. But when I try to run it, the game crashes: (full log) https://pastebin.com/88T5Weqk

I don't see anything obvious in my or BetterFPS code that could cause it. What do I need to do to make it run in dev environment?

**Comment by Guichaguri** [comment] 2017-05-21 16:22
The mod is not compiled for dev environment, that's why it doesn't work. I can give you a dev build tomorrow, if you want.

The only line of code that BetterFps changes is [this one](https://github.com/Guichaguri/BetterFps/blob/1.11/src/main/java/guichaguri/betterfps/patches/misc/FogPatch.java#L24). It adds that line in the start of `EntityRenderer.setupFog`.

**Comment by Guichaguri** [comment] 2017-05-21 16:31
I think I've found the problem, I'll try to fix it ASAP

**Comment by Niko-sk2x** [comment] 2017-05-21 16:42
I can make a dev build myself if that's the issue. I just didn't see any actual BetterFPS code in the stacktrace so I assumed ti was something wrong with bytecode transformation.

You said you found the problem - are you talking about the one I was trying to debug? I really wouldn't expect anyone to support my crazy hackery.

**Comment by Guichaguri** [comment] 2017-05-21 16:43
The problem is with the clouds option, for some reason, when they're disabled, the fog starts to render.

This is also related to #53. Feel free to close the issue in your mod, this is all BetterFps' fault :P

**Closed as completed** 2017-05-21 16:52 UTC
Labels: bug

**Comment by Guichaguri** [comment] 2017-05-21 17:02
Yep, this was definitely caused by an update. It doesn't happen with clouds enabled because `EntityRenderer.renderCloudsCheck` disables the fog.
I'd say it's a problem with the game itself, it leaves an inconsistent fog state after `EntityRenderer.renderWorldPass`

The whole point of BetterFps is to improve the performance of the game without conflicting with other mods. I don't care if your mod does some crazy hackery, I have to make them work together, or at least help you fixing it

**Comment by Guichaguri** [comment] 2017-05-21 17:15
I think this was the issue that was causing the fog to not work, I'll build your mod tomorrow and try it out. Feel free to reopen this issue :)

**Comment by Niko-sk2x** [comment] 2017-05-21 17:17
The bug report said there was too much fog above clounds level. And I even have trouble reproducing it.

**Comment by Niko-sk2x** [comment] 2017-05-21 17:22
I was able to reproduce it now. I will try to build that version of BetterFPS to test it. Now that I see how it happens what you said makes sense and my speculation was just completely wrong in every way possible.
