### ISSUE TITLE
Taylor’s algorithm messes up game

### ISSUE THREAD

**Issue by Dimentive** [Guichaguri/BetterFps#139] opened 2020-01-05 15:46 UTC
My friend tried Taylor’s algorithm, and it messed up his game. His player model was moving around like crazy. It looked like he was dancing. His view kept shifting all over the place too. The reason he tried this algorithm in the first place was that the JAR benchmark showed that Taylor’s algorithm was the fastest.

I did recently report the same thing happening with the random algorithm (#137), and it was closed as the random algorithm is just a joke, but the same is happening with Taylor’s algorithm, which is, presumably, not a joke algorithm.

### Versions
* **Minecraft:** 1.12.2
* **BetterFps:** 1.4.8 (latest)
* **Forge:** 14.23.5.2847 (latest for 1.12.2)

**Comment by Guichaguri** [comment] 2020-01-05 21:07
Duplicate of #62

**Closed as completed by Guichaguri** 2020-01-05 21:07 UTC
