### ISSUE TITLE
Limb Glitch

### ISSUE THREAD

**Issue by skeleton727** [Guichaguri/BetterFps#114] opened 2018-06-24 23:08 UTC
* Minecraft Version: 1.12.2
* BetterFps Version: 1.4.8
* Forge/LiteLoader Version (if any): 1.12.2-forge1.12.2-14.23.4.2709
* Crash Logs (if any): N/A
* Other Mods (if any): (Was part of Nature's Beauty modpack but I removed mods until I found the one that was causing it which was BetterFps, whenever.) Mods: betterundergound 1.1.2, BiomesOPlenty-1.12.2-7.0.1.2393-universal, Earthworks-1.12-1.3.6, jei_1.12.2-4.8.5.159, OptiFine_1.12.2_HD_U_D3 , Pam's HarvestCraft 1.12.2t , Xaeros_Minimap_1.14.9.1_Forge_1.12.

Video of Glitch or Bug: 
https://www.youtube.com/watch?v=U9CT22tW2rY&feature=youtu.be
---

**Comment by Guichaguri** [comment] 2018-06-24 23:20
It's the Taylor's Algorithm, change to another algorithm and it should work properly. Duplicate of #62

**Closed as completed by Guichaguri** 2018-06-24 23:20 UTC
Labels: bug, duplicate
